services:
  postgres:
    image: postgres:16-alpine
    container_name: hazeljs-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hazeljs
      POSTGRES_PASSWORD: hazeljs
      POSTGRES_DB: hazeljs_starter
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
